# fly.toml app configuration file generated for my-project-autumn-grass-6442 on 2025-02-20T19:48:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-project-autumn-grass-6442'
primary_region = 'cdg'

[build]
  dockerfile = "dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 8080

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
