# fly.toml app configuration file generated for my-project-rough-fire-9557 on 2025-02-20T15:28:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-project-rough-fire-9557'
primary_region = 'cdg'

[build image]
  dockerfile = "dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
